tasks:
  - name: Setup Java 17 and Build Spring Boot
    init: |
      # Install Java 17 via SDKMAN (automated - no prompts)
      echo "Y" | sdk install java 17.0.15-tem
      sdk default java 17.0.15-tem
      
      # Verify Java 17 is active
      java -version
      mvn -version
      
      # Build the project
      ./gradlew clean build
    command: |
      # Run Spring Boot application
      ./gradlew bootRun

ports:
  - port: 8080
    onOpen: open-preview

vscode:
  extensions:
    - vscjava.vscode-gradle  # Gradle 项目管理
    - redhat.java             # Java 语言支持
    - vscjava.vscode-spring-boot # Spring Boot 辅助
    - eamodio.gitlens         # 代码历史追踪
